import type { Node, Edge } from '@xyflow/react';
import type { NodeData, LifecycleEvent } from './types';

export const demoNodes: Node<NodeData>[] = [
  {
    id: 'note-1',
    type: 'lifecycleNode',
    position: { x: 0, y: 0 },
    data: {
      label: 'User Research Notes',
      category: 'note',
      status: 'active',
      description: 'Raw notes from user interviews and surveys',
      version: 2,
      lastUpdated: Date.now() - 300000,
      content: 'Users want real-time data, drag-and-drop dashboards, and team sharing...',
    },
  },
  {
    id: 'cid-1',
    type: 'lifecycleNode',
    position: { x: 340, y: 0 },
    data: {
      label: 'CID: Refine Notes',
      category: 'cid',
      status: 'active',
      description: 'Converts research notes into structured state objects',
      version: 1,
      lastUpdated: Date.now() - 240000,
    },
  },
  {
    id: 'state-1',
    type: 'lifecycleNode',
    position: { x: 680, y: 0 },
    data: {
      label: 'Product State',
      category: 'state',
      status: 'active',
      description: 'Canonical product definition and requirements',
      version: 3,
      lastUpdated: Date.now() - 120000,
      content: 'SaaS Analytics Platform — real-time dashboards, user segmentation, custom reports',
      sections: [
        { id: 's1', title: 'Product Vision', status: 'current' },
        { id: 's2', title: 'Core Features', status: 'current' },
        { id: 's3', title: 'User Personas', status: 'current' },
      ],
    },
  },
  {
    id: 'policy-1',
    type: 'lifecycleNode',
    position: { x: 1020, y: 0 },
    data: {
      label: 'Consistency Policy',
      category: 'policy',
      status: 'active',
      description: 'Ensures naming and branding stay consistent across all artifacts',
      version: 1,
      lastUpdated: Date.now() - 600000,
    },
  },
  {
    id: 'artifact-1',
    type: 'lifecycleNode',
    position: { x: 340, y: 250 },
    data: {
      label: 'PRD Document',
      category: 'artifact',
      status: 'active',
      description: 'Product Requirements Document',
      version: 4,
      lastUpdated: Date.now() - 60000,
      sections: [
        { id: 'a1', title: 'Overview', status: 'current' },
        { id: 'a2', title: 'Feature Specs', status: 'stale' },
        { id: 'a3', title: 'User Stories', status: 'current' },
        { id: 'a4', title: 'Success Metrics', status: 'current' },
      ],
    },
  },
  {
    id: 'artifact-2',
    type: 'lifecycleNode',
    position: { x: 680, y: 250 },
    data: {
      label: 'Technical Spec',
      category: 'artifact',
      status: 'stale',
      description: 'System architecture and API design',
      version: 2,
      lastUpdated: Date.now() - 180000,
      sections: [
        { id: 'b1', title: 'Architecture', status: 'stale' },
        { id: 'b2', title: 'API Design', status: 'stale' },
        { id: 'b3', title: 'Data Model', status: 'current' },
      ],
    },
  },
  {
    id: 'artifact-3',
    type: 'lifecycleNode',
    position: { x: 1020, y: 250 },
    data: {
      label: 'Pitch Deck',
      category: 'artifact',
      status: 'active',
      description: 'Investor presentation slides',
      version: 3,
      lastUpdated: Date.now() - 90000,
      sections: [
        { id: 'c1', title: 'Problem', status: 'current' },
        { id: 'c2', title: 'Solution', status: 'current' },
        { id: 'c3', title: 'Market Size', status: 'current' },
        { id: 'c4', title: 'Roadmap', status: 'stale' },
      ],
    },
  },
  {
    id: 'review-1',
    type: 'lifecycleNode',
    position: { x: 340, y: 500 },
    data: {
      label: 'Review Gate',
      category: 'review',
      status: 'reviewing',
      description: 'Pending approval for Feature Specs update',
      version: 1,
      lastUpdated: Date.now() - 30000,
    },
  },
  {
    id: 'cid-2',
    type: 'lifecycleNode',
    position: { x: 780, y: 500 },
    data: {
      label: 'CID: Propagate',
      category: 'cid',
      status: 'pending',
      description: 'Waiting to propagate state changes to stale artifacts',
      version: 1,
      lastUpdated: Date.now() - 15000,
    },
  },
];

export const demoEdges: Edge[] = [
  { id: 'e-n1-c1', source: 'note-1', target: 'cid-1', type: 'smoothstep', animated: true, style: { stroke: '#f59e0b', strokeWidth: 2 } },
  { id: 'e-c1-s1', source: 'cid-1', target: 'state-1', type: 'smoothstep', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
  { id: 'e-s1-a1', source: 'state-1', target: 'artifact-1', type: 'smoothstep', style: { stroke: '#06b6d4', strokeWidth: 2 } },
  { id: 'e-s1-a2', source: 'state-1', target: 'artifact-2', type: 'smoothstep', style: { stroke: '#06b6d4', strokeWidth: 2, strokeDasharray: '6 3' } },
  { id: 'e-s1-a3', source: 'state-1', target: 'artifact-3', type: 'smoothstep', style: { stroke: '#06b6d4', strokeWidth: 2 } },
  { id: 'e-p1-a3', source: 'policy-1', target: 'artifact-3', type: 'smoothstep', style: { stroke: '#64748b', strokeWidth: 1.5, strokeDasharray: '4 4' } },
  { id: 'e-p1-a2', source: 'policy-1', target: 'artifact-2', type: 'smoothstep', style: { stroke: '#64748b', strokeWidth: 1.5, strokeDasharray: '4 4' } },
  { id: 'e-a1-r1', source: 'artifact-1', target: 'review-1', type: 'smoothstep', animated: true, style: { stroke: '#f43f5e', strokeWidth: 2 } },
  { id: 'e-a2-c2', source: 'artifact-2', target: 'cid-2', type: 'smoothstep', animated: true, style: { stroke: '#8b5cf6', strokeWidth: 2, strokeDasharray: '6 3' } },
  { id: 'e-a3-c2', source: 'artifact-3', target: 'cid-2', type: 'smoothstep', style: { stroke: '#8b5cf6', strokeWidth: 1.5, strokeDasharray: '4 4' } },
];

export const demoEvents: LifecycleEvent[] = [
  { id: 'ev-1', type: 'refined', message: 'CID Agent refined user research notes into structured state', timestamp: Date.now() - 240000, nodeId: 'cid-1', agent: true },
  { id: 'ev-2', type: 'created', message: 'PRD Document generated from product state', timestamp: Date.now() - 200000, nodeId: 'artifact-1' },
  { id: 'ev-3', type: 'created', message: 'Technical Spec generated from product state', timestamp: Date.now() - 180000, nodeId: 'artifact-2' },
  { id: 'ev-4', type: 'edited', message: 'User edited Product Vision in state', timestamp: Date.now() - 120000, nodeId: 'state-1' },
  { id: 'ev-5', type: 'stale', message: 'Technical Spec marked stale — state changed', timestamp: Date.now() - 110000, nodeId: 'artifact-2', agent: true },
  { id: 'ev-6', type: 'regenerated', message: 'PRD Overview section regenerated', timestamp: Date.now() - 60000, nodeId: 'artifact-1', agent: true },
  { id: 'ev-7', type: 'created', message: 'Review gate created for Feature Specs update', timestamp: Date.now() - 30000, nodeId: 'review-1', agent: true },
  { id: 'ev-8', type: 'optimized', message: 'CID Agent queued propagation for stale artifacts', timestamp: Date.now() - 15000, nodeId: 'cid-2', agent: true },
];
